// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-V7b4kdsBiPhzEmk6hgyicgPeWp5ke-s',
    appId: '1:43456823173:web:ab53db3835f6ba17ca8eec',
    messagingSenderId: '43456823173',
    projectId: 'burak-basci-website',
    authDomain: 'burak-basci-website.firebaseapp.com',
    storageBucket: 'burak-basci-website.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJnZhq1d6-KCe6OTIj5083LPlnXjRVhlI',
    appId: '1:43456823173:android:90e0b61f53c70c43ca8eec',
    messagingSenderId: '43456823173',
    projectId: 'burak-basci-website',
    storageBucket: 'burak-basci-website.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlZmNY6XXkYmu6O3G4nixk7Ifz_Gr_JoQ',
    appId: '1:43456823173:ios:44071c255f8f9ae0ca8eec',
    messagingSenderId: '43456823173',
    projectId: 'burak-basci-website',
    storageBucket: 'burak-basci-website.appspot.com',
    iosClientId: '43456823173-hjcqdnjgbphlac3skq33oujd018ul7e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.burakBasciWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlZmNY6XXkYmu6O3G4nixk7Ifz_Gr_JoQ',
    appId: '1:43456823173:ios:b38db7000ba6fc3fca8eec',
    messagingSenderId: '43456823173',
    projectId: 'burak-basci-website',
    storageBucket: 'burak-basci-website.appspot.com',
    iosClientId: '43456823173-3kd9q9s2fa7c4hkpi0hsbu4ckghhoup5.apps.googleusercontent.com',
    iosBundleId: 'com.example.burakBasciWebsite.RunnerTests',
  );
}
